SELECT t1.dtRef,
    t1.idCustomer,
    t1.recenciaDias,
    t1.frequenciaDias,
    t1.valorPoints,
    t1.idadeBaseDias,
    t1.flEmail,
    t3.quantityPointsMorning,
    t3.quantityPointsAfternoon,
    t3.quantityPointsEvening,
    t3.pctPointsMorning,
    t3.pctPointsAfternoon,
    t3.pctPointsEvening,
    t3.quantityTransactionsMorning,
    t3.quantityTransactionsAfternoon,
    t3.quantityTransactionsEvening,
    t3.pctTransactionsMorning,
    t3.pctTransactionsAfternoon,
    t3.pctTransactionsEvening,
    t4.saldoPointsD21,
    t4.saldoPointsD14,
    t4.saldoPointsD7,
    t4.pointsAcumuladosD21,
    t4.pointsAcumuladosD14,
    t4.pointsAcumuladosD7,
    t4.pointsResgatadosD21,
    t4.pointsResgatadosD14,
    t4.pointsResgatadosD7,
    t4.saldoPoints,
    t4.pointsAcumuladosVida,
    t4.pointsResgatadosVida,
    t4.pointsPorDia,
    t5.quantityChatMessage,
    t5.quantityListaPresenca,
    t5.quantityResgatarPonei,
    t5.quantityTrocaPontos,
    t5.quantityPresencaStreak,
    t5.quantityAirflowLover,
    t5.quantityRLover,
    t5.pointsChatMessage,
    t5.pointsListaPresenca,
    t5.pointsResgatarPonei,
    t5.pointsTrocaPontos,
    t5.pointsPresencaStreak,
    t5.pointsAirflowLover,
    t5.pointsRLover,
    t5.pctChatMessage,
    t5.pctListaPresenca,
    t5.pctResgatarPonei,
    t5.pctTrocaPontos,
    t5.pctPresencaStreak,
    t5.pctAirflowLover,
    t5.pctRLover,
    t5.avgChatLive,
    t5.productMaxQuantity,
    t6.quantityDiasD21,
    t6.quantityDiasD14,
    t6.quantityDiasD7,
    t6.avgLiveMinutes,
    t6.sumLiveMinutes,
    t6.minLiveMinutes,
    t6.maxLiveMinutes,
    t6.quantityTransactionLive,
    t6.avgTransactionDay
FROM feature_store_general AS t1
    LEFT JOIN feature_store_horario AS t3 ON t1.idCustomer = t3.idCustomer
    AND t1.dtRef = t3.dtRef
    LEFT JOIN feature_store_pontos AS t4 ON t1.idCustomer = t4.idCustomer
    AND t1.dtRef = t4.dtRef
    LEFT JOIN feature_store_produtos AS t5 ON t1.idCustomer = t5.idCustomer
    AND t1.dtRef = t5.dtRef
    LEFT JOIN feature_store_transacoes AS t6 ON t1.idCustomer = t6.idCustomer
    AND t1.dtRef = t6.dtRef
WHERE t1.dtRef = (
        SELECT MAX(dtRef)
        FROM feature_store_general
    )